
## Bei "for-loops are evil" apply einführen

- apply performed als Ersatz für rowSums viel besser als for-loop
- Vergleich mit Schlüssel durch spaltenweisen logischen Vergleich, ganz 
ohne apply, mapply oder for Schleife
- Macht hier bereits ein Verweis auf lapply/replicate Sinn? ("The R way")

## Neues Kapitel: Anwendung: Trennschärfe als Funktion

Inhalte:

- Abstraktion als Prinzip in Programmierung -- aber überlegen, wann
  eine Abstraktion Sinn macht (kann man das voraussichtlich noch mal
  gebrauchen, bzw. hat man eine Analyse schon oft durchgeführt?)
- `if`-Statements zur Überprüfung der Korrektheit der Eingabe
- Teste auf Typ der Eingabe (`class(input) == "data.frame"`)
- `[, drop = FALSE]` -- man muss mehr aufpassen, wenn die Eingabe 
beliebig sein kann und nicht auf den einen Datensatz beschränkt ist, 
den man gerade bearbeitet (Kosten/Nutzen-Abrechnung: Wie viel 
Generalisierbarkeit lohnt sich?)

## Neues Kapitel: Anwendung: Invertierung von `data.frames`

## Neues Kapitel: Bivariate Zusammenhänge

- Scatterplots (+ random jitter)
- cor()
- cor.test()
- lm()
- abline()
- Ausblick: Multivariate Regression

## Anhang

- Trouble-Shooting
    + Objekte inspizieren (in Konsole ausführen)
    + Insbesondere: Existiert Spalte von data.frame?
    + table()
- Konsole ist "stuck", `+` bei der Eingabe -> in RStudio mit Esc beenden
- Im Zweifel: Environment aufräumen und Code neu durchführen -- 
  manchmal funktioniert es dann (vielleicht hat man ja auch vergessen,
  ein paar Zeilen Code überhaupt auszuführen)
- Fehlermeldungen: kryptisch, Meldung googeln hilft oftmals aber
- Einen Spaziergang machen und danach den Code noch mal anschauen
